name: "Greeting Action"
description: "Receives name and returns message"

inputs:
  username:
    required: true
    description: "User name"

outputs:
  message:
    description: "Greeting message"
    value: ${{ steps.set-output.outputs.message }}

runs:
  using: "composite"
  steps:
    - name: Set Output
      id: set-output
      run: echo "message=Hello ${{ inputs.username }}" >> $GITHUB_OUTPUT
      shell: bash

    - name: Run Java Program
      run: java ${{ inputs.file-name }}
      shell: bash