name: Greeting Workflow

on:
  push:
    

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:

      - name: Run Greeting Action
        id: greet-actions
        uses: ./.github/actions/java-build
        with:
          username: Milan

      - name: Show Greeting
        run: echo "${{steps.greet-action.outputs.message}}"
        